services:
    SunCat\MobileDetectBundle\DeviceDetector\MobileDetector:
        public: false

    SunCat\MobileDetectBundle\Helper\DeviceView:
        arguments:
            - '@?request_stack'
        calls:
            - [setCookieKey, ['%mobile_detect.cookie_key%']]
            - [setSwitchParam, ['%mobile_detect.switch_param%']]
            - [setCookieExpireDatetimeModifier, ['%mobile_detect.cookie_expire_datetime_modifier%']]

    SunCat\MobileDetectBundle\EventListener\RequestResponseListener:
        arguments:
            - '@SunCat\MobileDetectBundle\DeviceDetector\MobileDetector'
            - '@SunCat\MobileDetectBundle\Helper\DeviceView'
            - '@router'
            - '%mobile_detect.redirect%'
            - '%mobile_detect.switch_device_view.save_referer_path%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: handleRequest, priority: 1 }
            - { name: kernel.event_listener, event: kernel.response, method: handleResponse }

    SunCat\MobileDetectBundle\DataCollector\DeviceDataCollector:
        autowire: true
        calls:
            - [setRedirectConfig, ['%mobile_detect.redirect%']]
        tags:
            - { name: data_collector, template: 'MobileDetectBundle:Collector:device', id: device.collector }

    SunCat\MobileDetectBundle\Twig\Extension\MobileDetectExtension:
        public: false
        arguments:
            - '@SunCat\MobileDetectBundle\DeviceDetector\MobileDetector'
            - '@SunCat\MobileDetectBundle\Helper\DeviceView'
            - '%mobile_detect.redirect%'
        calls:
            - [setRequestByRequestStack, ['@?request_stack']]
        tags:
            - { name: twig.extension }

    # Alias to prevent BC <3.3
    mobile_detect.mobile_detector.default : '@SunCat\MobileDetectBundle\DeviceDetector\MobileDetector'
    mobile_detect.mobile_detector: '@SunCat\MobileDetectBundle\DeviceDetector\MobileDetector'
    mobile_detect.device_view: '@SunCat\MobileDetectBundle\Helper\DeviceView'
    mobile_detect.request_listener: '@SunCat\MobileDetectBundle\EventListener\RequestResponseListener'
    mobile_detect_bundle.device.collector: '@SunCat\MobileDetectBundle\DataCollector\DeviceDataCollector'
    mobile_detect.twig.extension: '@SunCat\MobileDetectBundle\Twig\Extension\MobileDetectExtension'
